# Form implementation generated from reading ui file 'sequence_analysis_gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Sequence_analysis_window(object):
    def setupUi(self, Sequence_analysis_window):
        Sequence_analysis_window.setObjectName("Sequence_analysis_window")
        Sequence_analysis_window.resize(400, 650)
        Sequence_analysis_window.setMinimumSize(QtCore.QSize(400, 650))
        Sequence_analysis_window.setMaximumSize(QtCore.QSize(400, 700))
        self.centralwidget = QtWidgets.QWidget(parent=Sequence_analysis_window)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(150, 10, 131, 16))
        self.title_label.setObjectName("title_label")
        self.show_codon_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.show_codon_checkbox.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.show_codon_checkbox.setObjectName("show_codon_checkbox")
        self.translate_codon_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.translate_codon_checkbox.setGeometry(QtCore.QRect(20, 90, 80, 20))
        self.translate_codon_checkbox.setObjectName("translate_codon_checkbox")
        self.find_start_codon_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.find_start_codon_checkbox.setGeometry(QtCore.QRect(20, 120, 131, 20))
        self.find_start_codon_checkbox.setObjectName("find_start_codon_checkbox")
        self.amino_acid_count_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.amino_acid_count_checkbox.setGeometry(QtCore.QRect(20, 180, 151, 20))
        self.amino_acid_count_checkbox.setObjectName("amino_acid_count_checkbox")
        self.find_stop_codon_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.find_stop_codon_checkbox.setGeometry(QtCore.QRect(20, 150, 121, 20))
        self.find_stop_codon_checkbox.setObjectName("find_stop_codon_checkbox")
        self.product_prediction_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.product_prediction_checkbox.setGeometry(QtCore.QRect(20, 210, 151, 20))
        self.product_prediction_checkbox.setObjectName("product_prediction_checkbox")
        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(20, 290, 71, 16))
        self.result_label.setObjectName("result_label")
        self.run_methods_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.run_methods_button.setGeometry(QtCore.QRect(120, 250, 113, 32))
        self.run_methods_button.setObjectName("run_methods_button")
        self.METHOD_RESULTS_txt = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.METHOD_RESULTS_txt.setGeometry(QtCore.QRect(20, 320, 371, 251))
        self.METHOD_RESULTS_txt.setObjectName("METHOD_RESULTS_txt")
        self.return_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(120, 590, 113, 32))
        self.return_button.setObjectName("return_button")
        Sequence_analysis_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Sequence_analysis_window)
        self.statusbar.setObjectName("statusbar")
        Sequence_analysis_window.setStatusBar(self.statusbar)

        self.retranslateUi(Sequence_analysis_window)
        QtCore.QMetaObject.connectSlotsByName(Sequence_analysis_window)

    def retranslateUi(self, Sequence_analysis_window):
        _translate = QtCore.QCoreApplication.translate
        Sequence_analysis_window.setWindowTitle(_translate("Sequence_analysis_window", "Sequence analyzer"))
        self.title_label.setText(_translate("Sequence_analysis_window", "\" \" Analysis"))
        self.show_codon_checkbox.setText(_translate("Sequence_analysis_window", "Show Codon"))
        self.translate_codon_checkbox.setText(_translate("Sequence_analysis_window", "Translate"))
        self.find_start_codon_checkbox.setText(_translate("Sequence_analysis_window", "Find Start Codon"))
        self.amino_acid_count_checkbox.setText(_translate("Sequence_analysis_window", "Amino Acid Counts"))
        self.find_stop_codon_checkbox.setText(_translate("Sequence_analysis_window", "Find Stop Codon"))
        self.product_prediction_checkbox.setText(_translate("Sequence_analysis_window", "Product prediction"))
        self.result_label.setText(_translate("Sequence_analysis_window", "Results:"))
        self.run_methods_button.setText(_translate("Sequence_analysis_window", "Run methods"))
        self.METHOD_RESULTS_txt.setHtml(_translate("Sequence_analysis_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">RESULTS<br /></p></body></html>"))
        self.return_button.setText(_translate("Sequence_analysis_window", "Return"))
