# Form implementation generated from reading ui file 'sequence_input_gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RNA_txt = QtWidgets.QLabel(parent=self.centralwidget)
        self.RNA_txt.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.RNA_txt.setObjectName("RNA_txt")
        self.RNA_input = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.RNA_input.setGeometry(QtCore.QRect(10, 50, 480, 191))
        self.RNA_input.setObjectName("RNA_input")
        self.analyze_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.analyze_button.setGeometry(QtCore.QRect(90, 250, 113, 32))
        self.analyze_button.setObjectName("analyze_button")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 250, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.RNA_txt.raise_()
        self.analyze_button.raise_()
        self.RNA_input.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RNA_txt.setText(_translate("MainWindow", "Input RNA sequence or protein:"))
        self.analyze_button.setText(_translate("MainWindow", "Analyze"))
        self.pushButton.setText(_translate("MainWindow", "Clear"))
